require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/morris", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Morri. As you add validations to Morri, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Morri.create! valid_attributes
      get morris_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      morri = Morri.create! valid_attributes
      get morri_url(morri)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_morri_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      morri = Morri.create! valid_attributes
      get edit_morri_url(morri)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Morri" do
        expect {
          post morris_url, params: { morri: valid_attributes }
        }.to change(Morri, :count).by(1)
      end

      it "redirects to the created morri" do
        post morris_url, params: { morri: valid_attributes }
        expect(response).to redirect_to(morri_url(Morri.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Morri" do
        expect {
          post morris_url, params: { morri: invalid_attributes }
        }.to change(Morri, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post morris_url, params: { morri: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested morri" do
        morri = Morri.create! valid_attributes
        patch morri_url(morri), params: { morri: new_attributes }
        morri.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the morri" do
        morri = Morri.create! valid_attributes
        patch morri_url(morri), params: { morri: new_attributes }
        morri.reload
        expect(response).to redirect_to(morri_url(morri))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        morri = Morri.create! valid_attributes
        patch morri_url(morri), params: { morri: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested morri" do
      morri = Morri.create! valid_attributes
      expect {
        delete morri_url(morri)
      }.to change(Morri, :count).by(-1)
    end

    it "redirects to the morris list" do
      morri = Morri.create! valid_attributes
      delete morri_url(morri)
      expect(response).to redirect_to(morris_url)
    end
  end
end
